[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "articull"
authors = [{name = "Gryte Satas", email = "gsatas7@gmail.com"}]
dynamic = ["version", "description"]