name: snv_filter
channels:
- conda-forge
- bioconda
- anaconda
- defaults
dependencies:
- numpy
- scipy
- pandas 
- matplotlib
- seaborn
- R
- R-essentials
- pysam
- scikit-learn
- pandarallel 
- bedtools
